site_name: Tape-out Learning Notes

theme:
  name: material
  language: zh
  font:
    code: JetBrainsMono
  features:
    - navigation.instant

plugins:
  - search:
      lang:
        - zh
        - en
  - mkdocs-material

nav:
  - Home: docs/index.md
  - Simulation: docs/1_code_modification_and_simulation_workflow.md
  - FPGA: 2_FPGA_verification_workflow.md
  - Genus Synthesis: 3_genus_synthesis_workflow.md
  - Innovus Implementation: 4_innovus_backend_workflow.md
  - Virtuoso Implementation: 5_virtuoso_verification.md