globalNetConnect VDD_SRAM -type pgpin -pin VDD -all -override
globalNetConnect VSS -type pgpin -pin VSS -all -override

# define SRAM Power
# VDDCE and VDDPE are defined by rtl generated by SRAM_COMPILER
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_0 
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_0 
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_1 
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_1 
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_2 
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_2 
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_3 
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_3 
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_4
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_4 
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_5 
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_5
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_6
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_6
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $sram_7
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $sram_7

globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_0 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_0 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_1 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_1  -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_2 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_2 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_3 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_3 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_4 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_4 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_5 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_5 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDCE -sinst $rf_6 -override
globalNetConnect VDD_SRAM -type pgpin -pin VDDPE -sinst $rf_6 -override

globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_0 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_1 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_2 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_3 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_4 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_5 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_6 -override
globalNetConnect VSS -type pgpin -pin VSSE -sinst $sram_7 -override

globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_0
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_1
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_2
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_3
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_4
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_5
globalNetConnect VSS -type pgpin -pin VSSE -sinst $rf_6

globalNetConnect VDD_SRAM -type tiehi
globalNetConnect VSS -type tielo
